import {Dimensions} from 'react-native';
import React, {Component} from 'react';

//Size

export const screenHeight = {
  height5: Math.round((5 / 100) * Dimensions.get('window').height),

  height10: Math.round((10 / 100) * Dimensions.get('window').height),
  height13: Math.round((13 / 100) * Dimensions.get('window').height),
  height20: Math.round((20 / 100) * Dimensions.get('window').height),
  height25: Math.round((25 / 100) * Dimensions.get('window').height),
  height30: Math.round((30 / 100) * Dimensions.get('window').height),
  height35: Math.round((35 / 100) * Dimensions.get('window').height),
  height40: Math.round((40 / 100) * Dimensions.get('window').height),
  height45: Math.round((45 / 100) * Dimensions.get('window').height),

  height50: Math.round((50 / 100) * Dimensions.get('window').height),

  height55: Math.round((55 / 100) * Dimensions.get('window').height),

  height60: Math.round((60 / 100) * Dimensions.get('window').height),
  height65: Math.round((65 / 100) * Dimensions.get('window').height),
  height70: Math.round((70 / 100) * Dimensions.get('window').height),
  height75: Math.round((75 / 100) * Dimensions.get('window').height),
  height80: Math.round((80 / 100) * Dimensions.get('window').height),
  height100: Math.round(Dimensions.get('window').height),
};

export const screenWidth = {
  width100: Math.round(Dimensions.get('window').width),
  width50: Math.round((50 / 100) * Dimensions.get('window').width),
  width45: Math.round((45 / 100) * Dimensions.get('window').width),
  width40: Math.round((40 / 100) * Dimensions.get('window').width),
  width35: Math.round((35 / 100) * Dimensions.get('window').width),
  width25: Math.round((25 / 100) * Dimensions.get('window').width),
  width20: Math.round((20 / 100) * Dimensions.get('window').width),
  width65: Math.round((65 / 100) * Dimensions.get('window').width),
};

//Url
export const URL = {
  Url: 'http://192.168.43.100:5000/',
};
//colors
export const colors = {
  orange: '#F59E52',
  whiteLayer: 'rgba(255, 255, 255, 0.2)',
  orablu: ['#F59E52', '#482C6D'],
  orangeGradient: ['#F59E52', '#DB883F'],
  boxColor: ['#E79247', '#D85802'],
  inboxBarInActive: ['#fff', '#fff'],
  inboxBarActive: ['#6B379D', '#2B2F92'],
  inputBordercolor: '#9B9B9B',
  darkBlue: '#321755',
  purple: '#381C5C',
  white: '#FFFFFF',
  shadowColor: '#707070',
  gray: '#9B9B9B',
  link: 'rgba(57,62,70,0.6)',
  gray5d: '#5d5d5d',
  link: 'rgba(57,62,70,0.6)',
  fadewhite: 'rgba(255,255,255,0.3)',
  dullBlack: 'rgba(0,0,0,0.4)',
  darkyellow: '#F59E52',
  black: 'black',
  lightblue: '#0C233C',
  Black323: '#323643',
  gray666: '#676666',
  black2B: '#2B2B2B',
  lightgray: '#F5F5F5',
  grayd7: '#d7d7d7',
};

//Images
export const images = {
  // local1: require('../assets/images/other/local1.jpg'),
  appIcon: require('../assets/images/other/appicon.png'),

  logoDark: require('../assets/images/logoDark.png'),
  email: require('../assets/images/mail.png'),
  key: require('..//assets/images/key.png'),
  camera: require('../assets/images/photo-camera.png'),
  timing: require('../assets/images/clock.png'),
  dollar: require('../assets/images/dollar.png'),
  plus: require('../assets/images/plus.png'),
  camerdark: require('../assets/images/cameradark.png'),
  leftarrow: require('../assets/images/left-arrow.png'),
  LegalPaper: require('../assets/images/legal-paper.png'),
  logoSmall: require('../assets/images/logo-small.png'),
  lgoSmalluri: '../assets/images/logo-small.png',
  logout: require('../assets/images/logout.png'),
  HomeImg: require('../assets/images/other/HomeImg.png'),
  cart: require('../assets/images/cart.png'),
  facebookdark: require('../assets/images/facebookdark.png'),
  arrowright: require('../assets/images/arrow-right.png'),
  cartype: require('../assets/images/cartype.png'),
  carservice: require('../assets/images/service.png'),
  phone: require('../assets/images/phone.png'),
  mic: require('../assets/images/mic.png'),
  add: require('../assets/images/add.png'),
  delete: require('../assets/images/delete.png'),
  plusbox: require('../assets/images/plusbox.png'),
  Lightcamera: require('../assets/images/camerawhite.png'),
subtract: require('../assets/images/subtract.png'),
  percent: require('../assets/images/percent.png'),
  store: require('../assets/images/store.png'),
  picture: require('../assets/images/picture.png'),
  Company: require('../assets/images/Company.png'),
  location: require('../assets/images/location.png'),
  setting: require('../assets/images/settings.png'),
  success: require('../assets/images/success.png'),
  serach: require('../assets/images/search.png'),
  leftarrow: require('../assets/images/left-arrow.png'),
  rightarrow: require('../assets/images/right-arrow.png'),
  cross: require('../assets/images/cross.png'),
  username: require('../assets/images/username.png'),
  clock: require('../assets/images/clock.png'),
  Subject: require('../assets/images/subject.png'),
  stat: require('../assets/images/stat.png'),
  Question: require('../assets/images/question.png'),
  checkBoxEmpty: require('../assets/images/checkBoxEmpty.png'),
  checkBoxTick: require('../assets/images/checkboxtick.png'),
  calendar: require('../assets/images/calendar.png'),
  user: require('../assets/images/user.png'),
  member: require('../assets/images/other/Group.png'),
  support: require('../assets/images/support.png'),
  saved: require('../assets/images/bookmark.png'),
  searchBottom: require('../assets/images/searchBottom.png'),
  backArrow: require('../assets/images/backArrow.png'),
  date: require('../assets/images/calendarOrange.png'),
  dummy1: require('../assets/images/userImg.png'),
  arrowLong: require('../assets/images/arrowLong.png'),
  backarrowh: require('../assets/images/backarrowh.png'),
  complaints: require('../assets/images/complaints.png'),
  userPurple: require('../assets/images/userPurple.png'),
  logoutPurple: require('../assets/images/logoutPurple.png'),
  cancel: require('../assets/images/cancel.png'),
  editEmpty: require('../assets/images/pencil.png'),
  userIcon: require('../assets/images/userIcon.png'),
  legalIcon: require('../assets/images/legalIcon.png'),
  terms: require('../assets/images/terms.png'),
  help: require('../assets/images/help.png'),
  refer: require('../assets/images/refer.png'),
  chatBox: require('../assets/images/chatbox.png'),

  //others

  dummy1: require('../assets/images/other/dummy1.jpg'),
  userImg: require('../assets/images/userImg.png'),
  category: require('../assets/images/other/categoryImg.png'),
  carPaint: require('../assets/images/other/carPaint.jpg'),
  engine1: require('../assets/images/other/engine1.jpg'),
  engine: require('../assets/images/other/engine.jpg'),
  electric: require('../assets/images/other/electric.jpg'),
  body: require('../assets/images/other/body.jpg'),
};
